name: Frontend CI

on:
  push:
    branches:
      - '*'

jobs:
  FE-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Update this to your desired Node.js version
  
      - name: Clear npm Cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Lint and Format Code
        run: npm run lint

      - name: Build Node App
        run: npm run build

      - name: Test using Jest
        run: npm test

      - name: Install Code Coverage Tool
        run: npm install nyc -g

      - name: Generate Code Coverage
        run: nyc report --reporter=lcov

      - name: Publish Code Coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/lcov-report

      - name: Security Scan with npm audit
        run: npm audit --audit-level=moderate

      - name: Fix Vulnerabilities
        run: npm audit fix
