name: Frontend CI

on:
  push:
    branches:
      - '*'

jobs:
  FE-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies
        run: npm ci

      - name: Lint and Format Code
        run: npm run lint

      - name: Build Node App
        run: npm run build

      - name: Test using Jest
        run: npm test

      - name: Install Code Coverage Tool
        run: npm install nyc -g

      - name: Generate Code Coverage
        run: nyc report --reporter=lcov
      
      - name: Publish Code Coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/lcov-report

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk and Run Security Scan
        run: |
          snyk auth $SNYK_TOKEN
          snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Use the secret for SNYK_TOKEN

      - name: Fix Vulnerabilities
        run: snyk wizard
